spring:
  config:
    import: application-aws.yml

  cache:
    type: redis
  redis:
    host: localhost
    port: '6379'

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-secret: SlkNZu0kJbHTjn4UvSmRXMstGhyVRw99
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-id: ec21649244d584c3a764d02977a4c0ba
            scope: profile_nickname, account_email
            client-name: Kakao
            client-authentication-method: POST
        provider:
          kakao:
            user-name-attribute: id
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'

  servlet:
    multipart:
      enabled: 'true'
      max-file-size: 10MB
      max-request-size: 30MB



logging:
  level:
    jdbc:
      audit: 'off'
      connection: 'off'
      resultset: 'off'
      resultsettable: info
      sqlonly: 'off'
      sqltiming: info

jwt:
  secret:
    access-key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
    refresh-key: 7ZWt7ZW064Gd64KY6rOg64uk7J2067mZ7ZWY65+s7KCc7KO864+E6rCI6rmM

#jasypt.encryptor.bean = jasyptEncryptor
